version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
    - echo Installing
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
  build:
    commands:
    - ls
  post_build:
    commands:
    - echo Build completed on `date`
    - ls
artifacts:
    files:
        - scripts/start_server
        - scripts/stop_server
        - dist/*
        - appspec.yml
    discard-paths: yes
